name: Continuous Releases

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: 🧑‍🔧 Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Enable Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable

      - name: 👷 Bootstrap Packages
        run: pnpm run setup
        shell: bash
        env:
          NODE_ENV: production
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Preview Packages
        # Allow PR #52 previews for Testplane integration testing, but not fork PRs.
        if: >-
          github.event_name == 'push' ||
          (github.event.pull_request.number == 52 &&
           github.event.pull_request.head.repo.full_name == github.repository)
        run: >-
          pnpm exec pkg-pr-new publish --pnpm --no-compact --commentWithSha
          './packages/wdio-types' './packages/wdio-logger' './packages/wdio-protocols'
          './packages/wdio-repl' './packages/wdio-utils' './packages/wdio-config'
          './packages/webdriver' './packages/webdriverio' './packages/devtools'
